import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { formatCurrency } from './utils';
import {
  renderPdfHeader,
  renderPdfFooter,
  getBusinessContext,
  toTitleCase,
} from './pdfExportUtils';
import { savePdf } from './nativeDownload';
import { PDF_FONT, registerJakartaFonts } from './pdfFonts';

/**
 * Render a Business Statement PDF using the shared FinFlo header/footer
 * helpers so it looks like the other ops statements (cash-flow, loan, etc).
 *
 * Inputs are the same shape the /ledger/business-statement endpoint returns.
 */
export const exportBusinessStatement = async ({
  summary = {},
  categories = [],
  transactions = [],
  dateRange,
  userName = 'Admin',
  businessContext = null,
} = {}) => {
  const ctx = businessContext || getBusinessContext();
  const doc = new jsPDF();
  await registerJakartaFonts(doc);

  const periodLabel =
    dateRange?.from && dateRange?.to
      ? `${format(dateRange.from, 'MMM dd, yyyy')} - ${format(dateRange.to, 'MMM dd, yyyy')}`
      : 'All time';

  const startY = await renderPdfHeader(doc, {
    businessContext: ctx,
    title: 'Business Income Statement',
    leftDetails: [
      { label: 'Generated By', value: toTitleCase(userName) },
      { label: 'Report Type', value: 'Income & Fees' },
    ],
    rightDetails: [
      { label: 'Statement Period', value: periodLabel },
      { label: 'Generated On', value: format(new Date(), 'MMM dd, yyyy') },
    ],
  });

  let cursorY = startY + 4;

  // ── Summary block ──────────────────────────────────────────────────────
  doc.setFont(PDF_FONT, 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Summary', 14, cursorY);
  cursorY += 5;

  autoTable(doc, {
    startY: cursorY,
    head: [['Metric', 'Amount']],
    body: [
      ['Total income', formatCurrency(summary.totalIncome || 0)],
      ['Fee income', formatCurrency(summary.feeIncome || 0)],
      ['Non-fee income', formatCurrency(summary.nonFeeIncome || 0)],
      [
        'Transactions',
        (summary.transactionCount || 0).toLocaleString(),
      ],
    ],
    theme: 'grid',
    styles: { font: PDF_FONT, fontSize: 9, cellPadding: 2.5 },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      font: PDF_FONT,
      fontStyle: 'bold',
    },
    columnStyles: {
      1: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 14, right: 14 },
  });
  cursorY = doc.lastAutoTable.finalY + 8;

  // ── Category breakdown ─────────────────────────────────────────────────
  if (categories.length > 0) {
    doc.setFont(PDF_FONT, 'bold');
    doc.setFontSize(11);
    doc.text('Income by category', 14, cursorY);
    cursorY += 5;

    autoTable(doc, {
      startY: cursorY,
      head: [['Category', 'Type', 'Entries', '% of total', 'Amount']],
      body: categories.map((c) => [
        c.label,
        c.isFee ? 'Fee' : 'Income',
        String(c.count || 0),
        `${c.percentage || 0}%`,
        formatCurrency(c.total || 0),
      ]),
      foot: [
        [
          {
            content: 'Total',
            colSpan: 4,
            styles: { halign: 'right', fontStyle: 'bold' },
          },
          {
            content: formatCurrency(summary.totalIncome || 0),
            styles: { halign: 'right', fontStyle: 'bold' },
          },
        ],
      ],
      theme: 'striped',
      styles: { font: PDF_FONT, fontSize: 9, cellPadding: 2.5 },
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [255, 255, 255],
        font: PDF_FONT,
        fontStyle: 'bold',
      },
      footStyles: {
        fillColor: [241, 245, 249],
        textColor: [15, 23, 42],
        font: PDF_FONT,
      },
      columnStyles: {
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'right' },
      },
      margin: { left: 14, right: 14 },
    });
    cursorY = doc.lastAutoTable.finalY + 8;
  }

  // ── Transactions table ─────────────────────────────────────────────────
  doc.setFont(PDF_FONT, 'bold');
  doc.setFontSize(11);
  doc.text('Transactions', 14, cursorY);
  cursorY += 5;

  if (transactions.length === 0) {
    doc.setFont(PDF_FONT, 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text('No income transactions in this period.', 14, cursorY + 4);
  } else {
    autoTable(doc, {
      startY: cursorY,
      head: [['Date', 'Description', 'Category', 'Entity', 'Amount']],
      body: transactions.map((t) => [
        format(new Date(t.date), 'dd MMM yyyy'),
        t.description || '—',
        (t.category || '—').replace(/_/g, ' '),
        toTitleCase(t.member?.name || t.customer?.name || '—'),
        formatCurrency(t.amount || 0),
      ]),
      foot: [
        [
          {
            content: 'Total',
            colSpan: 4,
            styles: { halign: 'right', fontStyle: 'bold' },
          },
          {
            content: formatCurrency(summary.totalIncome || 0),
            styles: { halign: 'right', fontStyle: 'bold' },
          },
        ],
      ],
      theme: 'striped',
      styles: { font: PDF_FONT, fontSize: 8, cellPadding: 2 },
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [255, 255, 255],
        font: PDF_FONT,
        fontStyle: 'bold',
      },
      footStyles: {
        fillColor: [241, 245, 249],
        textColor: [15, 23, 42],
        font: PDF_FONT,
      },
      columnStyles: {
        4: { halign: 'right', fontStyle: 'bold' },
      },
      margin: { left: 14, right: 14 },
    });
  }

  renderPdfFooter(doc, { businessContext: ctx });

  const filename = `business-statement-${format(
    dateRange?.from || new Date(),
    'yyyyMMdd',
  )}-${format(dateRange?.to || new Date(), 'yyyyMMdd')}.pdf`;
  await savePdf(doc, filename);
};
