import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from './utils';
import { format } from 'date-fns';

export const exportCashFlowStatement = async (
  data = {},
  dateRange,
  userName = 'Admin',
) => {
  const { repayments = [], summary = {} } = data;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Header Logo/App Name
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229); // Primary Indigo color
  doc.text('FINFLOW', 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'normal');
  doc.text('CASH FLOW ANALYSIS', 14, 28);

  doc.setFontSize(9);
  doc.text(
    `Statement Period: ${format(dateRange.from, 'MMM dd, yyyy')} - ${format(dateRange.to, 'MMM dd, yyyy')}`,
    14,
    38,
  );
  doc.text(`Generated by: ${userName}`, pageWidth - 60, 38);

  doc.setDrawColor(230);
  doc.line(14, 42, pageWidth - 14, 42);

  // Performance Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Financial Performance Summary', 14, 55);

  autoTable(doc, {
    startY: 60,
    body: [
      ['Total Cash Inflow', formatCurrency(summary.inflow || 0)],
      ['Total Deposits', formatCurrency(summary.deposits || 0)],
      ['Total Disbursements', formatCurrency(summary.outflow || 0)],
      ['Interest Profit', formatCurrency(summary.profit || 0)],
      ['Operating Expenses', formatCurrency(summary.expenses || 0)],
      ['Total Transactions', (summary.totalTransactions || 0).toString()],
    ],
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', width: 60, textColor: [100, 100, 100] },
      1: { fontStyle: 'bold', textColor: [0, 0, 0], halign: 'right' },
    },
  });

  // Transaction Details
  const tableY = (doc.lastAutoTable?.finalY || 80) + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Transaction Statement', 14, tableY);

  if (repayments && repayments.length > 0) {
    autoTable(doc, {
      startY: tableY + 5,
      head: [['Date', 'Description', 'Entity', 'Ref', 'Amount']],
      body: repayments.map((t) => [
        format(new Date(t.date), 'MMM dd, yyyy'),
        t.type === 'repayment' ? 'Loan Repayment' : 'Member Deposit',
        t.entityName || t.customer?.name || t.member?.name || 'N/A', // Handle both new and old structure if needed
        t.reference || t.loan?.loanId || 'Deposit',
        formatCurrency(t.amount),
      ]),
      theme: 'grid',
      headStyles: {
        fillColor: [79, 70, 229],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10,
      },
      styles: { fontSize: 9, cellPadding: 4 },
      columnStyles: { 4: { halign: 'right', fontStyle: 'bold' } },
      alternateRowStyles: { fillColor: [250, 251, 255] },
    });
  } else {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150);
    doc.text('No transaction records found for this period.', 14, tableY + 15);
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);

    // Page number
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 25,
      doc.internal.pageSize.height - 10,
    );

    // Legal disclaimer
    doc.text(
      'FINFLOW - Secure Financial Management Ecosystem. This is a computer-generated document.',
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' },
    );

    // Generation timestamp
    doc.text(
      `Processed at: ${new Date().toLocaleString()}`,
      14,
      doc.internal.pageSize.height - 10,
    );
  }

  const fileName = `FinFlo_Statement_${format(dateRange.from, 'yyyyMMdd')}_${format(dateRange.to, 'yyyyMMdd')}.pdf`;
  doc.save(fileName);
};
