import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from './utils';
import { format } from 'date-fns';
import { renderPdfHeader, renderPdfFooter, getBusinessContext } from './pdfExportUtils';

export const exportCashFlowStatement = async (
  data = {},
  dateRange,
  userName = 'Admin',
  businessContext = null,
) => {
  const { repayments = [], summary = {} } = data;
  const ctx = businessContext || getBusinessContext();
  const doc = new jsPDF();

  const startY = await renderPdfHeader(doc, {
    businessContext: ctx,
    title: 'Cash Flow Analysis Statement',
    leftDetails: [
      { label: 'Generated By', value: userName },
      { label: 'Report Type', value: 'Cash Flow Analysis' },
    ],
    rightDetails: [
      { label: 'Statement Period', value: `${format(dateRange.from, 'MMM dd, yyyy')} - ${format(dateRange.to, 'MMM dd, yyyy')}` },
      { label: 'Generated On', value: new Date().toLocaleDateString() },
    ],
  });

  // ── Performance Summary ──
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Financial Performance Summary', 14, startY);

  autoTable(doc, {
    startY: startY + 4,
    head: [['Metric', 'Value']],
    body: [
      ['Total Cash Inflow', formatCurrency(summary.inflow || 0)],
      ['Total Deposits', formatCurrency(summary.deposits || 0)],
      ['Total Disbursements', formatCurrency(summary.outflow || 0)],
      ['Interest Profit', formatCurrency(summary.profit || 0)],
      ['Operating Expenses', formatCurrency(summary.expenses || 0)],
      ['Total Transactions', (summary.totalTransactions || 0).toString()],
    ],
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [100, 100, 100] },
      1: { fontStyle: 'bold', textColor: [0, 0, 0], halign: 'right' },
    },
    alternateRowStyles: { fillColor: [250, 250, 255] },
    margin: { left: 14, right: 14 },
  });

  // ── Transaction Details ──
  const tableY = (doc.lastAutoTable?.finalY || 80) + 10;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Detailed Transaction Statement', 14, tableY);

  if (repayments && repayments.length > 0) {
    autoTable(doc, {
      startY: tableY + 4,
      head: [['Date', 'Description', 'Entity', 'Ref', 'Amount']],
      body: repayments.map((t) => [
        format(new Date(t.date), 'MMM dd, yyyy'),
        t.type === 'repayment' ? 'Loan Repayment' : 'Member Deposit',
        t.entityName || t.customer?.name || t.member?.name || 'N/A',
        t.reference || t.loan?.loanId || 'Deposit',
        formatCurrency(t.amount),
      ]),
      theme: 'grid',
      headStyles: {
        fillColor: [79, 70, 229],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: { 4: { halign: 'right', fontStyle: 'bold' } },
      alternateRowStyles: { fillColor: [250, 250, 255] },
      margin: { left: 14, right: 14 },
    });
  } else {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150);
    doc.text('No transaction records found for this period.', 14, tableY + 12);
  }

  renderPdfFooter(doc, { businessContext: ctx });

  const fileName = `FinFlo_Statement_${format(dateRange.from, 'yyyyMMdd')}_${format(dateRange.to, 'yyyyMMdd')}.pdf`;
  doc.save(fileName);
};
