import { useState, useEffect } from 'react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import {
  Download,
  DollarSign,
  TrendingUp,
  TrendingDown,
  ShieldCheck,
  Layers,
  Landmark,
  Banknote,
  ArrowRightLeft,
  Users,
  AlertTriangle,
  Building2,
  Clock,
  Loader2,
  Activity,
} from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import api from '@/lib/axios';
import { formatFullCurrency as formatCurrency, cn } from '@/lib/utils';
import { savePdf } from '@/lib/nativeDownload';
import { toast } from 'sonner';

const BalanceSheetTab = () => {
  const user = JSON.parse(localStorage.getItem('user') || '{}') || {};
  const [balanceSheet, setBalanceSheet] = useState(null);
  const [loadingBalanceSheet, setLoadingBalanceSheet] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const fetchBalanceSheet = async () => {
    try {
      setLoadingBalanceSheet(true);
      const { data: bsData } = await api.get('/reports/balance-sheet');
      setBalanceSheet(bsData);
    } catch (error) {
      toast.error('Failed to fetch Balance Sheet');
    } finally {
      setLoadingBalanceSheet(false);
    }
  };

  useEffect(() => {
    if (!balanceSheet) {
      fetchBalanceSheet();
    }
  }, []);

  const exportBalanceSheetPDF = async () => {
    if (!balanceSheet) return;
    try {
      setIsExporting(true);
      const {
        renderPdfHeader,
        renderPdfFooter,
        getBusinessContext,
        toTitleCase,
        renderPdfSignatures,
      } = await import('@/lib/pdfExportUtils');
      const ctx = getBusinessContext();
      const doc = new jsPDF();

      const startY = await renderPdfHeader(doc, {
        businessContext: ctx,
        title: 'Balance Sheet',
        leftDetails: [
          { label: 'Report Type', value: 'Balance Sheet' },
          { label: 'Generated By', value: toTitleCase(user.name || 'Admin') },
        ],
        rightDetails: [
          { label: 'As Of Date', value: new Date().toLocaleDateString() },
          { label: 'Generated On', value: new Date().toLocaleString() },
        ],
      });

      const bs = balanceSheet;
      const tableData = [
        [
          {
            content: 'ASSETS',
            colSpan: 2,
            styles: {
              fillColor: [220, 252, 231],
              fontStyle: 'bold',
              textColor: [5, 150, 105],
              fontSize: 10,
            },
          },
        ],
        ['Cash at Hand / Bank', formatCurrency(bs.assets?.cashAtHand || 0)],
        ['Loans Receivable', formatCurrency(bs.assets?.loansReceivable || 0)],
        ...(bs.assets?.termDepositsHeld > 0
          ? [['Term Deposits Held', formatCurrency(bs.assets.termDepositsHeld)]]
          : []),
        [
          { content: 'Total Assets', styles: { fontStyle: 'bold' } },
          {
            content: formatCurrency(bs.assets?.totalAssets || 0),
            styles: { fontStyle: 'bold' },
          },
        ],
        [
          {
            content: 'LIABILITIES',
            colSpan: 2,
            styles: {
              fillColor: [254, 226, 226],
              fontStyle: 'bold',
              textColor: [225, 29, 72],
              fontSize: 10,
            },
          },
        ],
        [
          'Member Current Accounts',
          formatCurrency(bs.liabilities?.memberCurrentAccounts || 0),
        ],
        [
          'Member Saving Accounts',
          formatCurrency(bs.liabilities?.memberSavingAccounts || 0),
        ],
        ...(bs.liabilities?.memberShareCapital > 0
          ? [
              [
                'Member Share Capital',
                formatCurrency(bs.liabilities.memberShareCapital),
              ],
            ]
          : []),
        ...(bs.liabilities?.termDepositObligations > 0
          ? [
              [
                'Term Deposit Obligations',
                formatCurrency(bs.liabilities.termDepositObligations),
              ],
            ]
          : []),
        [
          { content: 'Total Liabilities', styles: { fontStyle: 'bold' } },
          {
            content: formatCurrency(bs.liabilities?.totalLiabilities || 0),
            styles: { fontStyle: 'bold' },
          },
        ],
        [
          {
            content: 'EQUITY',
            colSpan: 2,
            styles: {
              fillColor: [224, 231, 255],
              fontStyle: 'bold',
              textColor: [79, 70, 229],
              fontSize: 10,
            },
          },
        ],
        ['   Interest Earned', formatCurrency(bs.equity?.interestEarned || 0)],
        ...(bs.equity?.feeIncome > 0
          ? [['   Fee Income', formatCurrency(bs.equity.feeIncome)]]
          : []),
        [
          {
            content: '   Less: Profit Distributed',
            styles: { textColor: [239, 68, 68] },
          },
          {
            content:
              '(' + formatCurrency(bs.equity?.profitDistributed || 0) + ')',
            styles: { textColor: [239, 68, 68] },
          },
        ],
        [
          {
            content: '   Less: Operating Expenses',
            styles: { textColor: [239, 68, 68] },
          },
          {
            content:
              '(' + formatCurrency(bs.equity?.operatingExpenses || 0) + ')',
            styles: { textColor: [239, 68, 68] },
          },
        ],
        [
          { content: 'Retained Earnings', styles: { fontStyle: 'bold' } },
          {
            content: formatCurrency(bs.equity?.retainedEarnings || 0),
            styles: { fontStyle: 'bold' },
          },
        ],
        [
          { content: 'Business Capital', styles: { fontStyle: 'bold' } },
          {
            content: formatCurrency(bs.equity?.businessCapital || 0),
            styles: { fontStyle: 'bold' },
          },
        ],
        [
          { content: 'Total Equity', styles: { fontStyle: 'bold' } },
          {
            content: formatCurrency(bs.equity?.totalEquity || 0),
            styles: { fontStyle: 'bold' },
          },
        ],
        [
          {
            content: 'BALANCE VERIFICATION',
            styles: {
              fontStyle: 'bold',
              fontSize: 11,
              fillColor: bs.balanceCheck?.isBalanced
                ? [5, 150, 105]
                : [245, 158, 11],
              textColor: 255,
            },
          },
          {
            content: bs.balanceCheck?.isBalanced
              ? 'BALANCED'
              : 'Discrepancy: ' +
                formatCurrency(bs.balanceCheck?.discrepancy || 0),
            styles: {
              fontStyle: 'bold',
              fontSize: 11,
              fillColor: bs.balanceCheck?.isBalanced
                ? [5, 150, 105]
                : [245, 158, 11],
              textColor: 255,
            },
          },
        ],
      ];

      autoTable(doc, {
        startY,
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 4 },
        columnStyles: { 1: { halign: 'right' } },
        alternateRowStyles: { fillColor: [250, 250, 255] },
        margin: { left: 14, right: 14 },
      });

      const finalY = doc.lastAutoTable?.finalY || startY + 20;
      await renderPdfSignatures(doc, { startY: finalY, businessContext: ctx });
      renderPdfFooter(doc, { businessContext: ctx });
      await savePdf(
        doc,
        'Balance_Sheet_' + new Date().toISOString().split('T')[0] + '.pdf',
      );
      toast.success('Balance Sheet PDF downloaded');
    } catch (error) {
      console.error(error);
      toast.error('Failed to export Balance Sheet PDF');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
      <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden">
        <CardContent className="p-4 sm:p-6">
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <div className="flex items-center gap-4 min-w-0">
              <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-teal-500 to-teal-600 shadow-lg shadow-teal-500/25">
                <Landmark size={20} className="text-white" />
              </div>
              <div className="min-w-0">
                <h2 className="text-base font-black tracking-tight truncate">
                  Balance Sheet
                </h2>
                <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5">
                  Formal Assets = Liabilities + Equity statement
                  {balanceSheet?.generatedAt && (
                    <span className="ml-2 text-muted-foreground/40">
                      · {new Date(balanceSheet.generatedAt).toLocaleString()}
                    </span>
                  )}
                </p>
              </div>
            </div>
            <div className="flex gap-2 shrink-0">
              <Button
                onClick={exportBalanceSheetPDF}
                variant="outline"
                disabled={!balanceSheet || isExporting}
                className="rounded-full text-[10px] font-black uppercase tracking-widest px-5 h-9 gap-2"
              >
                {isExporting ? (
                  <Loader2 size={12} className="animate-spin" />
                ) : (
                  <Download size={12} />
                )}
                Export PDF
              </Button>
              <Button
                onClick={fetchBalanceSheet}
                variant="outline"
                className="rounded-full text-[10px] font-black uppercase tracking-widest px-5 h-9 gap-2"
              >
                <Loader2
                  size={12}
                  className={loadingBalanceSheet ? 'animate-spin' : ''}
                />
                Refresh
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {loadingBalanceSheet ? (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
          <div className="grid gap-4 sm:gap-6 grid-cols-2 lg:grid-cols-4">
            {[0, 1, 2, 3].map((i) => (
              <Card
                key={i}
                className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-2xl overflow-hidden"
              >
                <CardContent className="p-4 sm:p-5 space-y-2">
                  <Skeleton className="h-3 w-24 rounded-full" />
                  <Skeleton className="h-7 w-32 rounded-lg" />
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {[0, 1, 2].map((i) => (
              <Card
                key={i}
                className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden"
              >
                <CardHeader className="p-4 sm:p-6">
                  <div className="flex items-center gap-4">
                    <Skeleton className="w-12 h-12 rounded-2xl" />
                    <div className="flex-1 space-y-2">
                      <Skeleton className="h-5 w-40 rounded-lg" />
                      <Skeleton className="h-3 w-64 rounded-lg" />
                    </div>
                    <Skeleton className="h-8 w-24 rounded-full" />
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="px-6 py-3 space-y-3">
                    {[0, 1, 2].map((j) => (
                      <div
                        key={j}
                        className="flex justify-between items-center"
                      >
                        <Skeleton className="h-4 w-1/3 rounded-lg" />
                        <Skeleton className="h-4 w-1/5 rounded-lg" />
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      ) : balanceSheet ? (
        <>
          {/* Summary Cards */}
          <div className="grid gap-4 sm:gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-4">
            <div className="bg-card border border-border/50 rounded-2xl p-4 sm:p-5 space-y-1">
              <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                Total Assets
              </p>
              <p className="text-lg sm:text-xl font-black text-emerald-600 dark:text-emerald-400 tabular-nums">
                {formatCurrency(balanceSheet.assets?.totalAssets || 0)}
              </p>
            </div>
            <div className="bg-card border border-border/50 rounded-2xl p-4 sm:p-5 space-y-1">
              <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                Total Liabilities
              </p>
              <p className="text-lg sm:text-xl font-black text-rose-600 dark:text-rose-400 tabular-nums">
                {formatCurrency(
                  balanceSheet.liabilities?.totalLiabilities || 0,
                )}
              </p>
            </div>
            <div className="bg-card border border-border/50 rounded-2xl p-4 sm:p-5 space-y-1">
              <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                Total Equity
              </p>
              <p className="text-lg sm:text-xl font-black text-indigo-600 dark:text-indigo-400 tabular-nums">
                {formatCurrency(balanceSheet.equity?.totalEquity || 0)}
              </p>
            </div>
            <div className="bg-card border border-border/50 rounded-2xl p-4 sm:p-5 space-y-1">
              <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                Balance Check
              </p>
              <p
                className={cn(
                  'text-lg sm:text-xl font-black tabular-nums',
                  balanceSheet.balanceCheck?.isBalanced
                    ? 'text-emerald-600 dark:text-emerald-400'
                    : 'text-amber-600 dark:text-amber-400',
                )}
              >
                {balanceSheet.balanceCheck?.isBalanced
                  ? '✓ Balanced'
                  : formatCurrency(balanceSheet.balanceCheck?.discrepancy || 0)}
              </p>
            </div>
          </div>

          {/* Detailed Tables */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
            <div className="flex flex-col gap-6 h-full">
              {/* Assets Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col flex-1">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-lg shadow-emerald-500/25">
                        <Banknote size={20} className="text-white" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Assets
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          Resources owned
                        </CardDescription>
                      </div>
                    </div>
                    <span className="tabular-nums font-black text-lg text-emerald-600 shrink-0">
                      {formatCurrency(balanceSheet.assets?.totalAssets || 0)}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="p-0 flex-1">
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                        <tr>
                          <th className="px-6 py-3">Account</th>
                          <th className="px-6 py-3 text-right">Balance</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <Landmark
                              size={14}
                              className="text-muted-foreground"
                            />{' '}
                            Cash at Hand / Bank
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium">
                            {formatCurrency(
                              balanceSheet.assets?.cashAtHand || 0,
                            )}
                          </td>
                        </tr>
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <DollarSign
                              size={14}
                              className="text-muted-foreground"
                            />{' '}
                            Loans Receivable
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium">
                            {formatCurrency(
                              balanceSheet.assets?.loansReceivable || 0,
                            )}
                          </td>
                        </tr>
                        {balanceSheet.assets?.termDepositsHeld > 0 && (
                          <tr className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 font-medium flex items-center gap-2">
                              <ShieldCheck
                                size={14}
                                className="text-muted-foreground"
                              />{' '}
                              Term Deposits Held
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums font-medium">
                              {formatCurrency(
                                balanceSheet.assets.termDepositsHeld,
                              )}
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                  <div className="md:hidden flex flex-col divide-y divide-border/20">
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <Landmark size={16} className="text-muted-foreground" />
                        Cash at Hand / Bank
                      </div>
                      <div className="text-right tabular-nums font-black">
                        {formatCurrency(balanceSheet.assets?.cashAtHand || 0)}
                      </div>
                    </div>
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <DollarSign
                          size={16}
                          className="text-muted-foreground"
                        />
                        Loans Receivable
                      </div>
                      <div className="text-right tabular-nums font-black">
                        {formatCurrency(
                          balanceSheet.assets?.loansReceivable || 0,
                        )}
                      </div>
                    </div>
                    {balanceSheet.assets?.termDepositsHeld > 0 && (
                      <div className="p-4 flex items-center justify-between">
                        <div className="font-bold flex items-center gap-2 text-sm">
                          <ShieldCheck
                            size={16}
                            className="text-muted-foreground"
                          />
                          Term Deposits Held
                        </div>
                        <div className="text-right tabular-nums font-black">
                          {formatCurrency(balanceSheet.assets.termDepositsHeld)}
                        </div>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Balance Verification Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col mt-6">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className={cn(
                        "p-3 rounded-2xl shrink-0 shadow-lg",
                        balanceSheet.balanceCheck?.isBalanced 
                          ? "bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-emerald-500/25"
                          : "bg-gradient-to-br from-rose-500 to-amber-500 shadow-rose-500/25"
                      )}>
                        {balanceSheet.balanceCheck?.isBalanced ? (
                          <ShieldCheck size={20} className="text-white" />
                        ) : (
                          <AlertTriangle size={20} className="text-white" />
                        )}
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Balance Check
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          {balanceSheet.balanceCheck?.isBalanced
                            ? 'Assets perfectly match Liabilities + Equity'
                            : 'Discrepancy detected (A ≠ L + E)'}
                        </CardDescription>
                      </div>
                    </div>
                    <span className={cn(
                      "tabular-nums font-black text-lg shrink-0",
                      balanceSheet.balanceCheck?.isBalanced ? "text-emerald-600" : "text-rose-600"
                    )}>
                      {balanceSheet.balanceCheck?.isBalanced ? (
                        'BALANCED'
                      ) : (
                        `Discrepancy: ${formatCurrency(balanceSheet.balanceCheck?.discrepancy || 0)}`
                      )}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="p-0 flex-1 flex flex-col justify-end">
                  <div className="flex flex-wrap items-center justify-center gap-x-4 gap-y-2 text-xs text-muted-foreground font-medium py-6 px-4 bg-muted/5 text-center mt-auto">
                    <span className="tabular-nums text-emerald-600 dark:text-emerald-400 font-bold">
                      {formatCurrency(balanceSheet.assets?.totalAssets || 0)}
                    </span>
                    <span className="text-muted-foreground/50">=</span>
                    <span className="tabular-nums text-rose-600 dark:text-rose-400 font-bold">
                      {formatCurrency(balanceSheet.liabilities?.totalLiabilities || 0)}
                    </span>
                    <span className="text-muted-foreground/50">+</span>
                    <span className="tabular-nums text-indigo-600 dark:text-indigo-400 font-bold">
                      {formatCurrency(balanceSheet.equity?.totalEquity || 0)}
                    </span>
                    <span className="text-muted-foreground/40 ml-1">
                      (Assets = Liabilities + Equity)
                    </span>
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="flex flex-col gap-6 h-full">
              {/* Liabilities Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col flex-1">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-rose-500 to-rose-600 shadow-lg shadow-rose-500/25">
                        <ArrowRightLeft size={20} className="text-white" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Liabilities
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          Obligations owed
                        </CardDescription>
                      </div>
                    </div>
                    <span className="tabular-nums font-black text-lg text-rose-600 shrink-0">
                      {formatCurrency(
                        balanceSheet.liabilities?.totalLiabilities || 0,
                      )}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                        <tr>
                          <th className="px-6 py-3">Account</th>
                          <th className="px-6 py-3 text-right">Balance</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <Users
                              size={14}
                              className="text-muted-foreground"
                            />{' '}
                            Member Current Accounts
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium">
                            {formatCurrency(
                              balanceSheet.liabilities?.memberCurrentAccounts ||
                                0,
                            )}
                          </td>
                        </tr>
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <Activity
                              size={14}
                              className="text-muted-foreground"
                            />{' '}
                            Member Saving Accounts
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium">
                            {formatCurrency(
                              balanceSheet.liabilities?.memberSavingAccounts ||
                                0,
                            )}
                          </td>
                        </tr>
                        {balanceSheet.liabilities?.memberShareCapital > 0 && (
                          <tr className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 font-medium flex items-center gap-2">
                              <Layers
                                size={14}
                                className="text-muted-foreground"
                              />{' '}
                              Member Share Capital
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums font-medium">
                              {formatCurrency(
                                balanceSheet.liabilities.memberShareCapital,
                              )}
                            </td>
                          </tr>
                        )}
                        {balanceSheet.liabilities?.termDepositObligations >
                          0 && (
                          <tr className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 font-medium flex items-center gap-2">
                              <Clock
                                size={14}
                                className="text-muted-foreground"
                              />{' '}
                              Term Deposit Obligations
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums font-medium">
                              {formatCurrency(
                                balanceSheet.liabilities.termDepositObligations,
                              )}
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                  <div className="md:hidden flex flex-col divide-y divide-border/20">
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <Users size={16} className="text-muted-foreground" />
                        Member Current Accounts
                      </div>
                      <div className="text-right tabular-nums font-black">
                        {formatCurrency(
                          balanceSheet.liabilities?.memberCurrentAccounts || 0,
                        )}
                      </div>
                    </div>
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <Activity size={16} className="text-muted-foreground" />
                        Member Saving Accounts
                      </div>
                      <div className="text-right tabular-nums font-black">
                        {formatCurrency(
                          balanceSheet.liabilities?.memberSavingAccounts || 0,
                        )}
                      </div>
                    </div>
                    {balanceSheet.liabilities?.memberShareCapital > 0 && (
                      <div className="p-4 flex items-center justify-between">
                        <div className="font-bold flex items-center gap-2 text-sm">
                          <Layers size={16} className="text-muted-foreground" />
                          Member Share Capital
                        </div>
                        <div className="text-right tabular-nums font-black">
                          {formatCurrency(
                            balanceSheet.liabilities.memberShareCapital,
                          )}
                        </div>
                      </div>
                    )}
                    {balanceSheet.liabilities?.termDepositObligations > 0 && (
                      <div className="p-4 flex items-center justify-between">
                        <div className="font-bold flex items-center gap-2 text-sm">
                          <Clock size={16} className="text-muted-foreground" />
                          Term Deposit Obligations
                        </div>
                        <div className="text-right tabular-nums font-black">
                          {formatCurrency(
                            balanceSheet.liabilities.termDepositObligations,
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Equity Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-indigo-500 to-indigo-600 shadow-lg shadow-indigo-500/25">
                        <TrendingUp size={20} className="text-white" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Equity
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          Retained earnings and capital
                        </CardDescription>
                      </div>
                    </div>
                    <span className="tabular-nums font-black text-lg text-indigo-600 shrink-0">
                      {formatCurrency(balanceSheet.equity?.totalEquity || 0)}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                        <tr>
                          <th className="px-6 py-3">Account</th>
                          <th className="px-6 py-3 text-right">Balance</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <TrendingUp
                              size={14}
                              className="text-emerald-500"
                            />{' '}
                            Interest Earned
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium text-emerald-600">
                            {formatCurrency(
                              balanceSheet.equity?.interestEarned || 0,
                            )}
                          </td>
                        </tr>
                        {balanceSheet.equity?.feeIncome > 0 && (
                          <tr className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 font-medium flex items-center gap-2">
                              <DollarSign
                                size={14}
                                className="text-emerald-500"
                              />{' '}
                              Fee Income
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums font-medium text-emerald-600">
                              {formatCurrency(balanceSheet.equity.feeIncome)}
                            </td>
                          </tr>
                        )}
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2 italic text-muted-foreground">
                            <TrendingDown size={14} className="text-rose-500" />{' '}
                            Less: Profit Distributed
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium text-rose-500">
                            (
                            {formatCurrency(
                              balanceSheet.equity?.profitDistributed || 0,
                            )}
                            )
                          </td>
                        </tr>
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2 italic text-muted-foreground">
                            <TrendingDown size={14} className="text-rose-500" />{' '}
                            Less: Operating Expenses
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium text-rose-500">
                            (
                            {formatCurrency(
                              balanceSheet.equity?.operatingExpenses || 0,
                            )}
                            )
                          </td>
                        </tr>
                        {balanceSheet.equity?.savingProfitDistributed > 0 && (
                          <tr className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 font-medium flex items-center gap-2 italic text-muted-foreground">
                              <TrendingDown
                                size={14}
                                className="text-rose-500"
                              />{' '}
                              Less: Saving Profit Paid
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums font-medium text-rose-500">
                              (
                              {formatCurrency(
                                balanceSheet.equity.savingProfitDistributed,
                              )}
                              )
                            </td>
                          </tr>
                        )}
                        {balanceSheet.equity?.shareProfitDistributed > 0 && (
                          <tr className="hover:bg-muted/10 transition-colors">
                            <td className="px-6 py-3 font-medium flex items-center gap-2 italic text-muted-foreground">
                              <TrendingDown
                                size={14}
                                className="text-rose-500"
                              />{' '}
                              Less: Share Profit Paid
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums font-medium text-rose-500">
                              (
                              {formatCurrency(
                                balanceSheet.equity.shareProfitDistributed,
                              )}
                              )
                            </td>
                          </tr>
                        )}
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <Building2
                              size={14}
                              className="text-muted-foreground"
                            />{' '}
                            Business Capital
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium">
                            {formatCurrency(
                              balanceSheet.equity?.businessCapital || 0,
                            )}
                          </td>
                        </tr>
                        <tr className="bg-indigo-500/5">
                          <td className="px-6 py-3 font-black text-foreground/90 flex items-center gap-2">
                            Retained Earnings
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-black">
                            {formatCurrency(
                              balanceSheet.equity?.retainedEarnings || 0,
                            )}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div className="md:hidden flex flex-col divide-y divide-border/20">
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <TrendingUp size={16} className="text-emerald-500" />
                        Interest Earned
                      </div>
                      <div className="text-right tabular-nums font-black text-emerald-600">
                        {formatCurrency(
                          balanceSheet.equity?.interestEarned || 0,
                        )}
                      </div>
                    </div>
                    {balanceSheet.equity?.feeIncome > 0 && (
                      <div className="p-4 flex items-center justify-between">
                        <div className="font-bold flex items-center gap-2 text-sm">
                          <DollarSign size={16} className="text-emerald-500" />
                          Fee Income
                        </div>
                        <div className="text-right tabular-nums font-black text-emerald-600">
                          {formatCurrency(balanceSheet.equity.feeIncome)}
                        </div>
                      </div>
                    )}
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm italic text-muted-foreground">
                        <TrendingDown size={16} className="text-rose-500" />
                        Less: Profit Distributed
                      </div>
                      <div className="text-right tabular-nums font-black text-rose-500">
                        (
                        {formatCurrency(
                          balanceSheet.equity?.profitDistributed || 0,
                        )}
                        )
                      </div>
                    </div>
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm italic text-muted-foreground">
                        <TrendingDown size={16} className="text-rose-500" />
                        Less: Operating Expenses
                      </div>
                      <div className="text-right tabular-nums font-black text-rose-500">
                        (
                        {formatCurrency(
                          balanceSheet.equity?.operatingExpenses || 0,
                        )}
                        )
                      </div>
                    </div>
                    {balanceSheet.equity?.savingProfitDistributed > 0 && (
                      <div className="p-4 flex items-center justify-between">
                        <div className="font-bold flex items-center gap-2 text-sm italic text-muted-foreground">
                          <TrendingDown size={16} className="text-rose-500" />
                          Less: Saving Profit Paid
                        </div>
                        <div className="text-right tabular-nums font-black text-rose-500">
                          (
                          {formatCurrency(
                            balanceSheet.equity.savingProfitDistributed,
                          )}
                          )
                        </div>
                      </div>
                    )}
                    {balanceSheet.equity?.shareProfitDistributed > 0 && (
                      <div className="p-4 flex items-center justify-between">
                        <div className="font-bold flex items-center gap-2 text-sm italic text-muted-foreground">
                          <TrendingDown size={16} className="text-rose-500" />
                          Less: Share Profit Paid
                        </div>
                        <div className="text-right tabular-nums font-black text-rose-500">
                          (
                          {formatCurrency(
                            balanceSheet.equity.shareProfitDistributed,
                          )}
                          )
                        </div>
                      </div>
                    )}
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <Building2
                          size={16}
                          className="text-muted-foreground"
                        />
                        Business Capital
                      </div>
                      <div className="text-right tabular-nums font-black">
                        {formatCurrency(
                          balanceSheet.equity?.businessCapital || 0,
                        )}
                      </div>
                    </div>
                    <div className="p-4 flex items-center justify-between bg-indigo-500/5">
                      <div className="font-black text-foreground/90 flex items-center gap-2 text-sm">
                        Retained Earnings
                      </div>
                      <div className="text-right tabular-nums font-black">
                        {formatCurrency(
                          balanceSheet.equity?.retainedEarnings || 0,
                        )}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Equation Footer moved to Balance Verification Card */}
        </>
      ) : (
        <div className="text-center py-12 bg-card rounded-3xl border border-border/50 text-muted-foreground">
          No balance sheet data available.
        </div>
      )}
    </div>
  );
};

export default BalanceSheetTab;
