import { useState, useEffect } from 'react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import {
  Download,
  DollarSign,
  TrendingUp,
  TrendingDown,
  FileText,
  Users,
} from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import { DateRangePicker } from '@/components/ui/date-range-picker';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import api from '@/lib/axios';
import { formatFullCurrency as formatCurrency, cn } from '@/lib/utils';
import { savePdf } from '@/lib/nativeDownload';
import { toast } from 'sonner';

const ProfitLossTab = () => {
  const user = JSON.parse(localStorage.getItem('user') || '{}') || {};
  const [pnl, setPnL] = useState(null);
  const [loadingPnL, setLoadingPnL] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [dateRange, setDateRange] = useState({
    from: new Date(
      new Date().getFullYear() - 1,
      new Date().getMonth(),
      new Date().getDate(),
    ),
    to: new Date(),
  });

  const fetchPnL = async () => {
    if (!dateRange?.from || !dateRange?.to) return;
    try {
      setLoadingPnL(true);
      const sDate = format(dateRange.from, 'yyyy-MM-dd');
      const eDate = format(dateRange.to, 'yyyy-MM-dd');
      const { data: pnlData } = await api.get(
        `/reports/profit-loss?startDate=${sDate}&endDate=${eDate}`,
      );
      setPnL(pnlData);
    } catch (error) {
      toast.error('Failed to fetch Profit & Loss report');
    } finally {
      setLoadingPnL(false);
    }
  };

  useEffect(() => {
    if (dateRange?.from && dateRange?.to) {
      fetchPnL();
    }
  }, [dateRange]);

  const exportAdvancedPDF = async () => {
    try {
      setIsExporting(true);
      const {
        renderPdfHeader,
        renderPdfFooter,
        getBusinessContext,
        toTitleCase,
        renderPdfSignatures,
      } = await import('@/lib/pdfExportUtils');
      const ctx = getBusinessContext();
      const doc = new jsPDF();

      const startY = await renderPdfHeader(doc, {
        businessContext: ctx,
        title: 'Profit & Loss Statement',
        leftDetails: [
          { label: 'Report Type', value: 'Income Statement' },
          { label: 'Generated By', value: toTitleCase(user.name || 'Admin') },
        ],
        rightDetails: [
          {
            label: 'Period',
            value: `${format(dateRange.from, 'PPP')} - ${format(dateRange.to, 'PPP')}`,
          },
          { label: 'Generated On', value: new Date().toLocaleString() },
        ],
      });

      if (pnl) {
        const expensesList = Object.entries(pnl.expenses?.breakdown || {}).map(
          ([key, val]) => [
            `   - ${key.charAt(0).toUpperCase() + key.slice(1)}`,
            formatCurrency(val),
          ],
        );
        const distributionsList = Object.entries(
          pnl.distributions?.breakdown || {},
        ).map(([key, val]) => [
          `   - ${key.charAt(0).toUpperCase() + key.slice(1)}`,
          formatCurrency(val),
        ]);

        const tableData = [
          [
            {
              content: 'REVENUE',
              colSpan: 2,
              styles: {
                fillColor: [243, 244, 246],
                fontStyle: 'bold',
                textColor: 0,
              },
            },
          ],
          ['Interest Earned', formatCurrency(pnl.revenue?.interestEarned || 0)],
          [
            {
              content: 'Total Gross Revenue',
              styles: { fontStyle: 'bold', textColor: [16, 185, 129] },
            },
            {
              content: formatCurrency(pnl.revenue?.totalRevenue || 0),
              styles: { fontStyle: 'bold', textColor: [16, 185, 129] },
            },
          ],
          [
            {
              content: 'OPERATING EXPENSES',
              colSpan: 2,
              styles: {
                fillColor: [243, 244, 246],
                fontStyle: 'bold',
                textColor: 0,
              },
            },
          ],
          ...expensesList,
          [
            {
              content: 'Total Expenses',
              styles: { fontStyle: 'bold', textColor: [239, 68, 68] },
            },
            {
              content: formatCurrency(pnl.expenses?.totalExpenses || 0),
              styles: { fontStyle: 'bold', textColor: [239, 68, 68] },
            },
          ],
          [
            {
              content: 'DISTRIBUTIONS',
              colSpan: 2,
              styles: {
                fillColor: [243, 244, 246],
                fontStyle: 'bold',
                textColor: 0,
              },
            },
          ],
          ...distributionsList,
          [
            {
              content: 'Total Distributions',
              styles: { fontStyle: 'bold', textColor: [245, 158, 11] },
            },
            {
              content: formatCurrency(
                pnl.distributions?.totalDistributions || 0,
              ),
              styles: { fontStyle: 'bold', textColor: [245, 158, 11] },
            },
          ],
          [
            {
              content: 'NET INCOME',
              styles: {
                fontStyle: 'bold',
                fontSize: 12,
                fillColor: [64, 53, 100],
                textColor: 255,
              },
            },
            {
              content: formatCurrency(pnl.netIncome || 0),
              styles: {
                fontStyle: 'bold',
                fontSize: 12,
                fillColor: [64, 53, 100],
                textColor: 255,
              },
            },
          ],
        ];

        autoTable(doc, {
          startY,
          body: tableData,
          theme: 'grid',
          styles: { fontSize: 10, cellPadding: 4 },
          columnStyles: { 1: { halign: 'right' } },
          alternateRowStyles: { fillColor: [250, 250, 255] },
          margin: { left: 14, right: 14 },
        });
      }

      const finalY = doc.lastAutoTable?.finalY || startY + 20;
      await renderPdfSignatures(doc, { startY: finalY, businessContext: ctx });
      renderPdfFooter(doc, { businessContext: ctx });
      await savePdf(
        doc,
        `Profit_Loss_${new Date().toISOString().split('T')[0]}.pdf`,
      );
      toast.success('Report downloaded successfully');
    } catch (error) {
      console.error(error);
      toast.error('Failed to export PDF');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
      <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden">
        <CardContent className="p-4 sm:p-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex items-center gap-4 min-w-0">
              <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-indigo-500 to-indigo-600 shadow-lg shadow-indigo-500/25">
                <FileText size={20} className="text-white" />
              </div>
              <div className="min-w-0">
                <h2 className="text-base font-black tracking-tight truncate">
                  Profit & Loss Statement
                </h2>
                <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5">
                  Income and expenses over a specific period
                </p>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto shrink-0">
              <DateRangePicker
                date={dateRange}
                setDate={setDateRange}
                className="w-full sm:w-auto"
              />
              <Button
                onClick={exportAdvancedPDF}
                isLoading={isExporting}
                disabled={loadingPnL || !pnl}
                variant="outline"
                className="rounded-full text-[10px] font-black uppercase tracking-widest px-5 h-9 gap-2 ml-auto shrink-0"
              >
                <Download size={14} />
                <span className="hidden sm:inline">Export PDF</span>
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {loadingPnL ? (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
          <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden">
            <CardContent className="p-6 sm:p-8">
              <div className="flex flex-col sm:flex-row items-center gap-6">
                <Skeleton className="w-16 h-16 rounded-full" />
                <div className="flex-1 space-y-3 text-center sm:text-left">
                  <Skeleton className="h-7 w-48 rounded-xl mx-auto sm:mx-0" />
                  <Skeleton className="h-4 w-36 rounded-lg mx-auto sm:mx-0" />
                </div>
                <Skeleton className="h-10 w-32 rounded-xl" />
              </div>
            </CardContent>
          </Card>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {[0, 1, 2, 3].map((i) => (
              <Card
                key={i}
                className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden"
              >
                <CardHeader className="p-4 sm:p-6">
                  <div className="flex items-center gap-4">
                    <Skeleton className="w-12 h-12 rounded-2xl" />
                    <div className="flex-1 space-y-2">
                      <Skeleton className="h-5 w-40 rounded-lg" />
                      <Skeleton className="h-3 w-64 rounded-lg" />
                    </div>
                    <Skeleton className="h-8 w-24 rounded-full" />
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="px-6 py-3 space-y-3">
                    {[0, 1].map((j) => (
                      <div
                        key={j}
                        className="flex justify-between items-center"
                      >
                        <Skeleton className="h-4 w-1/3 rounded-lg" />
                        <Skeleton className="h-4 w-1/5 rounded-lg" />
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      ) : pnl ? (
        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="space-y-6">
              {/* Gross Revenue Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-lg shadow-emerald-500/25">
                        <TrendingUp size={20} className="text-white" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Gross Revenue
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          Income from interest and fees
                        </CardDescription>
                      </div>
                    </div>
                    <div className="flex items-center gap-3 shrink-0">
                      <span className="tabular-nums font-black text-lg text-emerald-600">
                        {formatCurrency(pnl.revenue.totalRevenue || 0)}
                      </span>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="p-0 flex-1">
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                        <tr>
                          <th className="px-6 py-3">Source</th>
                          <th className="px-6 py-3 text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        <tr className="hover:bg-muted/10 transition-colors">
                          <td className="px-6 py-3 font-medium flex items-center gap-2">
                            <TrendingUp
                              size={14}
                              className="text-emerald-500"
                            />{' '}
                            Interest Earned
                          </td>
                          <td className="px-6 py-3 text-right tabular-nums font-medium">
                            {formatCurrency(pnl.revenue.interestEarned || 0)}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div className="md:hidden flex flex-col divide-y divide-border/20">
                    <div className="p-4 flex items-center justify-between">
                      <div className="font-bold flex items-center gap-2 text-sm">
                        <TrendingUp size={16} className="text-emerald-500" />
                        Interest Earned
                      </div>
                      <div className="text-right tabular-nums font-black text-emerald-600">
                        {formatCurrency(pnl.revenue.interestEarned || 0)}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Operating Expenses Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-rose-500 to-rose-600 shadow-lg shadow-rose-500/25">
                        <TrendingDown size={20} className="text-white" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Operating Expenses
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          Business operating costs
                        </CardDescription>
                      </div>
                    </div>
                    <div className="flex items-center gap-3 shrink-0">
                      <span className="tabular-nums font-black text-lg text-rose-600">
                        {formatCurrency(pnl.expenses.totalExpenses || 0)}
                      </span>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="p-0 flex-1">
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                        <tr>
                          <th className="px-6 py-3">Category</th>
                          <th className="px-6 py-3 text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        {Object.entries(pnl.expenses.breakdown || {}).length >
                        0 ? (
                          Object.entries(pnl.expenses.breakdown).map(
                            ([category, amount]) => (
                              <tr
                                key={category}
                                className="hover:bg-muted/10 transition-colors"
                              >
                                <td className="px-6 py-3 font-medium flex items-center gap-2 capitalize">
                                  <TrendingDown
                                    size={14}
                                    className="text-rose-500"
                                  />{' '}
                                  {category}
                                </td>
                                <td className="px-6 py-3 text-right tabular-nums font-medium">
                                  {formatCurrency(amount)}
                                </td>
                              </tr>
                            ),
                          )
                        ) : (
                          <tr>
                            <td
                              colSpan={2}
                              className="px-6 py-4 text-center text-muted-foreground italic text-xs"
                            >
                              No expenses recorded in this period.
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                  <div className="md:hidden flex flex-col divide-y divide-border/20">
                    {Object.entries(pnl.expenses.breakdown || {}).length > 0 ? (
                      Object.entries(pnl.expenses.breakdown).map(
                        ([category, amount]) => (
                          <div
                            key={category}
                            className="p-4 flex items-center justify-between"
                          >
                            <div className="font-bold flex items-center gap-2 text-sm capitalize">
                              <TrendingDown
                                size={16}
                                className="text-rose-500"
                              />
                              {category}
                            </div>
                            <div className="text-right tabular-nums font-black">
                              {formatCurrency(amount)}
                            </div>
                          </div>
                        ),
                      )
                    ) : (
                      <div className="p-6 text-center text-muted-foreground italic text-xs">
                        No expenses recorded in this period.
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="space-y-6">
              {/* Profit Distributions Card */}
              <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300 flex flex-col">
                <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-4 min-w-0">
                      <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-amber-500 to-amber-600 shadow-lg shadow-amber-500/25">
                        <Users size={20} className="text-white" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base font-black tracking-tight truncate">
                          Profit Distributions
                        </CardTitle>
                        <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">
                          Profits shared with members
                        </CardDescription>
                      </div>
                    </div>
                    <div className="flex items-center gap-3 shrink-0">
                      <span className="tabular-nums font-black text-lg text-amber-600">
                        {formatCurrency(
                          pnl.distributions.totalDistributions || 0,
                        )}
                      </span>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="p-0 flex-1">
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                        <tr>
                          <th className="px-6 py-3">Type</th>
                          <th className="px-6 py-3 text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20">
                        {Object.entries(pnl.distributions.breakdown || {})
                          .length > 0 ? (
                          Object.entries(pnl.distributions.breakdown).map(
                            ([type, amount]) => (
                              <tr
                                key={type}
                                className="hover:bg-muted/10 transition-colors"
                              >
                                <td className="px-6 py-3 font-medium flex items-center gap-2 capitalize">
                                  <TrendingDown
                                    size={14}
                                    className="text-amber-500"
                                  />{' '}
                                  {type} Profit
                                </td>
                                <td className="px-6 py-3 text-right tabular-nums font-medium">
                                  {formatCurrency(amount)}
                                </td>
                              </tr>
                            ),
                          )
                        ) : (
                          <tr>
                            <td
                              colSpan={2}
                              className="px-6 py-4 text-center text-muted-foreground italic text-xs"
                            >
                              No distributions recorded in this period.
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                  <div className="md:hidden flex flex-col divide-y divide-border/20">
                    {Object.entries(pnl.distributions.breakdown || {}).length >
                    0 ? (
                      Object.entries(pnl.distributions.breakdown).map(
                        ([type, amount]) => (
                          <div
                            key={type}
                            className="p-4 flex items-center justify-between"
                          >
                            <div className="font-bold flex items-center gap-2 text-sm capitalize">
                              <TrendingDown
                                size={16}
                                className="text-amber-500"
                              />
                              {type} Profit
                            </div>
                            <div className="text-right tabular-nums font-black">
                              {formatCurrency(amount)}
                            </div>
                          </div>
                        ),
                      )
                    ) : (
                      <div className="p-6 text-center text-muted-foreground italic text-xs">
                        No distributions recorded in this period.
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Net Income Card */}
              <Card
                className={cn(
                  'border shadow-sm rounded-[2rem] overflow-hidden transition-all duration-500',
                  (pnl.netIncome || 0) >= 0
                    ? 'border-emerald-500/30 bg-gradient-to-br from-emerald-500/5 to-emerald-600/5'
                    : 'border-rose-500/30 bg-gradient-to-br from-rose-500/5 to-rose-600/5',
                )}
              >
                <CardContent className="p-6 sm:p-8 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div className="flex items-center gap-4">
                    <div
                      className={cn(
                        'w-16 h-16 rounded-full flex items-center justify-center shrink-0 shadow-lg',
                        (pnl.netIncome || 0) >= 0
                          ? 'bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-emerald-500/30'
                          : 'bg-gradient-to-br from-rose-500 to-rose-600 shadow-rose-500/30',
                      )}
                    >
                      <DollarSign className="w-8 h-8 text-white" />
                    </div>
                    <div>
                      <h2 className="text-md sm:text-xl font-black tracking-tight uppercase">
                        Net Income
                      </h2>
                      <p className="text-xs text-muted-foreground font-medium mt-1">
                        Final bottom line for the period
                      </p>
                    </div>
                  </div>
                  <div
                    className={cn(
                      'text-3xl font-black tabular-nums tracking-tight',
                      (pnl.netIncome || 0) >= 0
                        ? 'text-emerald-600 dark:text-emerald-400'
                        : 'text-rose-600 dark:text-rose-400',
                    )}
                  >
                    {formatCurrency(pnl.netIncome || 0)}
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      ) : (
        <div className="text-center py-12 bg-card rounded-3xl border border-border/50 text-muted-foreground">
          Data unavailable.
        </div>
      )}
    </div>
  );
};

export default ProfitLossTab;
