import { useState, useEffect } from 'react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import {
  Download,
  DollarSign,
  TrendingUp,
  TrendingDown,
  ShieldCheck,
  Layers,
  Landmark,
  Banknote,
  ArrowRightLeft,
  Users,
  AlertTriangle,
  Building2,
} from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import api from '@/lib/axios';
import {
  formatFullCurrency as formatCurrency,
  formatCompactValue,
  cn,
} from '@/lib/utils';
import { savePdf } from '@/lib/nativeDownload';
import { toast } from 'sonner';

const TrialBalanceTab = () => {
  const user = JSON.parse(localStorage.getItem('user') || '{}') || {};
  const [trialBalance, setTrialBalance] = useState(null);
  const [loadingTrial, setLoadingTrial] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const fetchTrialBalance = async () => {
    try {
      setLoadingTrial(true);
      const { data: tbData } = await api.get('/reports/trial-balance');
      setTrialBalance(tbData);
    } catch (error) {
      toast.error('Failed to fetch Trial Balance');
    } finally {
      setLoadingTrial(false);
    }
  };

  useEffect(() => {
    if (!trialBalance) {
      fetchTrialBalance();
    }
  }, []);

  const exportAdvancedPDF = async () => {
    try {
      setIsExporting(true);
      const {
        renderPdfHeader,
        renderPdfFooter,
        getBusinessContext,
        toTitleCase,
        renderPdfSignatures,
      } = await import('@/lib/pdfExportUtils');
      const ctx = getBusinessContext();
      const doc = new jsPDF();

      const startY = await renderPdfHeader(doc, {
        businessContext: ctx,
        title: 'Trial Balance Statement',
        leftDetails: [
          { label: 'Report Type', value: 'Trial Balance' },
          { label: 'Generated By', value: toTitleCase(user.name || 'Admin') },
        ],
        rightDetails: [
          { label: 'As Of Date', value: new Date().toLocaleDateString() },
          { label: 'Generated On', value: new Date().toLocaleString() },
        ],
      });

      if (trialBalance) {
        const tableData = [
          [{ content: 'ASSETS', colSpan: 2, styles: { fillColor: [243, 244, 246], fontStyle: 'bold', textColor: 0 } }],
          ['Loans Receivable', formatCurrency(trialBalance.assets?.loansReceivable || 0)],
          ['Cash at Hand / Bank', formatCurrency(trialBalance.assets?.cashAtHand || 0)],
          [{ content: 'Total Assets', styles: { fontStyle: 'bold' } }, { content: formatCurrency(trialBalance.assets?.totalAssets || 0), styles: { fontStyle: 'bold' } }],
          [{ content: 'LIABILITIES', colSpan: 2, styles: { fillColor: [243, 244, 246], fontStyle: 'bold', textColor: 0 } }],
          ['Member Current Accounts', formatCurrency(trialBalance.liabilities?.memberCapital || 0)],
          ...((trialBalance.liabilities?.memberSavingAccounts || 0) > 0 ? [['Member Saving Accounts', formatCurrency(trialBalance.liabilities.memberSavingAccounts)]] : []),
          ...((trialBalance.liabilities?.memberShareCapital || 0) > 0 ? [['Member Share Capital', formatCurrency(trialBalance.liabilities.memberShareCapital)]] : []),
          [{ content: 'Total Liabilities', styles: { fontStyle: 'bold' } }, { content: formatCurrency(trialBalance.liabilities?.totalLiabilities || 0), styles: { fontStyle: 'bold' } }],
          [{ content: 'EQUITY', colSpan: 2, styles: { fillColor: [243, 244, 246], fontStyle: 'bold', textColor: 0 } }],
          ['Retained Earnings', formatCurrency(trialBalance.equity?.retainedEarnings || 0)],
          ['Business Capital', formatCurrency(trialBalance.equity?.businessCapital || 0)],
          [{ content: 'Total Equity', styles: { fontStyle: 'bold' } }, { content: formatCurrency(trialBalance.equity?.totalEquity || 0), styles: { fontStyle: 'bold' } }],
        ];

        autoTable(doc, {
          startY,
          body: tableData,
          theme: 'grid',
          styles: { fontSize: 10, cellPadding: 4 },
          columnStyles: { 1: { halign: 'right' } },
          alternateRowStyles: { fillColor: [250, 250, 255] },
          margin: { left: 14, right: 14 },
        });
      }

      const finalY = doc.lastAutoTable?.finalY || startY + 20;
      await renderPdfSignatures(doc, { startY: finalY, businessContext: ctx });
      renderPdfFooter(doc, { businessContext: ctx });

      await savePdf(doc, `Trial_Balance_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('Report downloaded successfully');
    } catch (error) {
      console.error(error);
      toast.error('Failed to export PDF');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
      <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden">
        <CardContent className="p-4 sm:p-6">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-4 min-w-0">
              <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-lg shadow-emerald-500/25">
                <Layers size={20} className="text-white" />
              </div>
              <div className="min-w-0">
                <h2 className="text-base font-black tracking-tight truncate">
                  Trial Balance Statement
                </h2>
                <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5">
                  Snapshot of assets, liabilities, and equity
                </p>
              </div>
            </div>
            <Button
              onClick={exportAdvancedPDF}
              isLoading={isExporting}
              disabled={loadingTrial || !trialBalance}
              variant="outline"
              className="rounded-full text-[10px] font-black uppercase tracking-widest px-5 h-9 gap-2 shrink-0"
            >
              <Download size={14} />
              <span className="hidden sm:inline">Export PDF</span>
            </Button>
          </div>
        </CardContent>
      </Card>

      {loadingTrial ? (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
          <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden">
            <CardContent className="p-6 sm:p-8">
              <div className="flex flex-col sm:flex-row items-center gap-6">
                <Skeleton className="w-20 h-20 rounded-full" />
                <div className="flex-1 space-y-3 text-center sm:text-left">
                  <Skeleton className="h-8 w-64 rounded-xl mx-auto sm:mx-0" />
                  <Skeleton className="h-4 w-48 rounded-lg mx-auto sm:mx-0" />
                </div>
                <div className="grid grid-cols-3 gap-4">
                  {[0, 1, 2].map((i) => (
                    <Skeleton key={i} className="h-16 w-24 rounded-xl" />
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
          {[0, 1].map((i) => (
            <Card key={i} className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden">
              <CardHeader className="p-4 sm:p-6">
                <div className="flex items-center gap-4">
                  <Skeleton className="w-12 h-12 rounded-2xl" />
                  <div className="flex-1 space-y-2">
                    <Skeleton className="h-5 w-40 rounded-lg" />
                    <Skeleton className="h-3 w-64 rounded-lg" />
                  </div>
                  <Skeleton className="h-8 w-24 rounded-full" />
                </div>
              </CardHeader>
              <CardContent className="p-0">
                <div className="px-6 py-3 space-y-3">
                  {[0, 1, 2].map((j) => (
                    <div key={j} className="flex justify-between items-center">
                      <Skeleton className="h-4 w-1/3 rounded-lg" />
                      <Skeleton className="h-4 w-1/5 rounded-lg" />
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : trialBalance ? (
        <div className="space-y-6">
          {/* HEALTH DASHBOARD */}
          <Card className={cn('border shadow-sm rounded-[2rem] overflow-hidden transition-all duration-500', (trialBalance.discrepancy || 0) === 0 ? 'border-emerald-500/30 bg-gradient-to-br from-emerald-500/5 to-emerald-600/5' : 'border-rose-500/30 bg-gradient-to-br from-rose-500/5 to-amber-500/5')}>
            <CardContent className="p-6 sm:p-8">
              <div className="flex flex-col sm:flex-row items-center gap-6">
                <div className={cn('w-20 h-20 rounded-full flex items-center justify-center shrink-0 shadow-xl', (trialBalance.discrepancy || 0) === 0 ? 'bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-emerald-500/30' : 'bg-gradient-to-br from-rose-500 to-amber-500 shadow-rose-500/30')}>
                  {(trialBalance.discrepancy || 0) === 0 ? (<ShieldCheck className="w-10 h-10 text-white" />) : (<AlertTriangle className="w-10 h-10 text-white" />)}
                </div>
                <div className="flex-1 text-center sm:text-left">
                  <h2 className="text-2xl font-black tracking-tight">
                    {(trialBalance.discrepancy || 0) === 0 ? (<>Trial Balance{' '}<span className="text-emerald-600 dark:text-emerald-400">Matched</span></>) : (<><span className="text-rose-600 dark:text-rose-400">Discrepancy</span>{' '}Detected</>)}
                  </h2>
                  <p className="text-xs text-muted-foreground font-medium mt-1">
                    Debits and Credits{' '}{(trialBalance.discrepancy || 0) === 0 ? 'are perfectly in balance' : 'do not match'}.
                  </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 shrink-0 w-full sm:w-fit">
                  <div className="text-center p-3 rounded-2xl bg-background/60 border border-border/40">
                    <div className="text-xl font-black text-emerald-600">{formatCompactValue(trialBalance.assets?.totalAssets || 0)}</div>
                    <div className="text-[9px] font-black uppercase tracking-widest text-muted-foreground/60 mt-0.5">Assets</div>
                  </div>
                  <div className="text-center p-3 rounded-2xl bg-background/60 border border-border/40">
                    <div className="text-xl font-black text-rose-600">{formatCompactValue(trialBalance.liabilities?.totalLiabilities || 0)}</div>
                    <div className="text-[9px] font-black uppercase tracking-widest text-muted-foreground/60 mt-0.5">Liabilities</div>
                  </div>
                  <div className="text-center p-3 rounded-2xl bg-background/60 border border-border/40">
                    <div className="text-xl font-black text-indigo-600">{formatCompactValue(trialBalance.equity?.totalEquity || 0)}</div>
                    <div className="text-[9px] font-black uppercase tracking-widest text-muted-foreground/60 mt-0.5">Equity</div>
                  </div>
                </div>
              </div>
              {(trialBalance.discrepancy || 0) !== 0 && (
                <div className="mt-5 p-4 rounded-2xl bg-rose-500/5 border border-rose-500/15 flex items-center justify-between gap-4 flex-wrap">
                  <div className="flex items-center gap-3">
                    <TrendingDown size={18} className="text-rose-500 shrink-0" />
                    <div>
                      <span className="text-xs font-bold text-rose-600 dark:text-rose-400">Discrepancy Amount</span>
                      <span className="text-[10px] text-muted-foreground ml-2">(Assets - [Liabilities + Equity])</span>
                    </div>
                  </div>
                  <span className="text-lg font-black tabular-nums text-rose-600 dark:text-rose-400">{formatCurrency(Math.abs(trialBalance.discrepancy || 0))}</span>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Debit Card */}
          <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300">
            <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
              <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-4 min-w-0">
                  <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-lg shadow-emerald-500/25">
                    <Banknote size={20} className="text-white" />
                  </div>
                  <div className="min-w-0">
                    <CardTitle className="text-base font-black tracking-tight truncate">Debit (Assets)</CardTitle>
                    <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">Total value of all assets</CardDescription>
                  </div>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <span className="tabular-nums font-black text-lg text-emerald-600">{formatCurrency(trialBalance.assets?.totalAssets || 0)}</span>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="hidden md:block overflow-x-auto">
                <table className="w-full text-sm text-left">
                  <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                    <tr><th className="px-6 py-3">Account Name</th><th className="px-6 py-3 text-right">Balance</th></tr>
                  </thead>
                  <tbody className="divide-y divide-border/20">
                    <tr className="hover:bg-muted/10 transition-colors">
                      <td className="px-6 py-3 font-medium flex items-center gap-2"><DollarSign size={14} className="text-muted-foreground" /> Loans Receivable</td>
                      <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.assets?.loansReceivable || 0)}</td>
                    </tr>
                    <tr className="hover:bg-muted/10 transition-colors">
                      <td className="px-6 py-3 font-medium flex items-center gap-2"><Landmark size={14} className="text-muted-foreground" /> Cash at Hand / Bank</td>
                      <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.assets?.cashAtHand || 0)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div className="md:hidden flex flex-col divide-y divide-border/20">
                <div className="p-4 flex items-center justify-between">
                  <div className="font-bold flex items-center gap-2 text-sm"><DollarSign size={16} className="text-muted-foreground" />Loans Receivable</div>
                  <div className="text-right tabular-nums font-black text-emerald-600">{formatCurrency(trialBalance.assets?.loansReceivable || 0)}</div>
                </div>
                <div className="p-4 flex items-center justify-between">
                  <div className="font-bold flex items-center gap-2 text-sm"><Landmark size={16} className="text-muted-foreground" />Cash at Hand / Bank</div>
                  <div className="text-right tabular-nums font-black text-emerald-600">{formatCurrency(trialBalance.assets?.cashAtHand || 0)}</div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Credit Card */}
          <Card className="border border-border/50 bg-card/50 backdrop-blur-sm shadow-sm rounded-[2rem] overflow-hidden transition-all duration-300">
            <CardHeader className="p-4 sm:p-6 pb-3 bg-muted/10 border-b border-border/30">
              <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-4 min-w-0">
                  <div className="p-3 rounded-2xl shrink-0 bg-gradient-to-br from-indigo-500 to-indigo-600 shadow-lg shadow-indigo-500/25">
                    <ArrowRightLeft size={20} className="text-white" />
                  </div>
                  <div className="min-w-0">
                    <CardTitle className="text-base font-black tracking-tight truncate">Credit (Liabilities & Equity)</CardTitle>
                    <CardDescription className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70 mt-0.5 truncate">Total obligations and capital</CardDescription>
                  </div>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <span className="tabular-nums font-black text-lg text-indigo-600">{formatCurrency((trialBalance.liabilities?.totalLiabilities || 0) + (trialBalance.equity?.totalEquity || 0))}</span>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="hidden md:block overflow-x-auto">
                <table className="w-full text-sm text-left">
                  <thead className="bg-muted/30 border-b border-border/50 text-[10px] uppercase tracking-wider text-muted-foreground font-black">
                    <tr><th className="px-6 py-3">Account Name</th><th className="px-6 py-3">Category</th><th className="px-6 py-3 text-right">Balance</th></tr>
                  </thead>
                  <tbody className="divide-y divide-border/20">
                    <tr className="hover:bg-muted/10 transition-colors">
                      <td className="px-6 py-3 font-medium flex items-center gap-2"><Users size={14} className="text-muted-foreground" /> Member Current Accounts</td>
                      <td className="px-6 py-3"><span className="inline-flex px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider bg-rose-500/10 text-rose-600 border border-rose-500/20">Liability</span></td>
                      <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.liabilities?.memberCapital || 0)}</td>
                    </tr>
                    {(trialBalance.liabilities?.memberSavingAccounts || 0) > 0 && (
                      <tr className="hover:bg-muted/10 transition-colors">
                        <td className="px-6 py-3 font-medium flex items-center gap-2"><Users size={14} className="text-muted-foreground" /> Member Saving Accounts</td>
                        <td className="px-6 py-3"><span className="inline-flex px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider bg-rose-500/10 text-rose-600 border border-rose-500/20">Liability</span></td>
                        <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.liabilities.memberSavingAccounts)}</td>
                      </tr>
                    )}
                    {(trialBalance.liabilities?.memberShareCapital || 0) > 0 && (
                      <tr className="hover:bg-muted/10 transition-colors">
                        <td className="px-6 py-3 font-medium flex items-center gap-2"><Users size={14} className="text-muted-foreground" /> Member Share Capital</td>
                        <td className="px-6 py-3"><span className="inline-flex px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider bg-rose-500/10 text-rose-600 border border-rose-500/20">Liability</span></td>
                        <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.liabilities.memberShareCapital)}</td>
                      </tr>
                    )}
                    <tr className="hover:bg-muted/10 transition-colors">
                      <td className="px-6 py-3 font-medium flex items-center gap-2"><Building2 size={14} className="text-muted-foreground" /> Business Capital</td>
                      <td className="px-6 py-3"><span className="inline-flex px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider bg-indigo-500/10 text-indigo-600 border border-indigo-500/20">Equity</span></td>
                      <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.equity?.businessCapital || 0)}</td>
                    </tr>
                    <tr className="hover:bg-muted/10 transition-colors">
                      <td className="px-6 py-3 font-medium flex items-center gap-2"><TrendingUp size={14} className="text-muted-foreground" /> Retained Earnings</td>
                      <td className="px-6 py-3"><span className="inline-flex px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider bg-indigo-500/10 text-indigo-600 border border-indigo-500/20">Equity</span></td>
                      <td className="px-6 py-3 text-right tabular-nums font-medium">{formatCurrency(trialBalance.equity?.retainedEarnings || 0)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div className="md:hidden flex flex-col divide-y divide-border/20">
                <div className="p-4 flex items-center justify-between">
                  <div><div className="font-bold flex items-center gap-2 text-sm"><Users size={16} className="text-muted-foreground" />Member Current Accounts</div><span className="inline-flex px-2 py-1 mt-2 rounded-lg text-[9px] font-black uppercase tracking-wider bg-rose-500/10 text-rose-600 border border-rose-500/20">Liability</span></div>
                  <div className="text-right tabular-nums font-black">{formatCurrency(trialBalance.liabilities?.memberCapital || 0)}</div>
                </div>
                {(trialBalance.liabilities?.memberSavingAccounts || 0) > 0 && (
                  <div className="p-4 flex items-center justify-between">
                    <div><div className="font-bold flex items-center gap-2 text-sm"><Users size={16} className="text-muted-foreground" />Member Saving Accounts</div><span className="inline-flex px-2 py-1 mt-2 rounded-lg text-[9px] font-black uppercase tracking-wider bg-rose-500/10 text-rose-600 border border-rose-500/20">Liability</span></div>
                    <div className="text-right tabular-nums font-black">{formatCurrency(trialBalance.liabilities.memberSavingAccounts)}</div>
                  </div>
                )}
                {(trialBalance.liabilities?.memberShareCapital || 0) > 0 && (
                  <div className="p-4 flex items-center justify-between">
                    <div><div className="font-bold flex items-center gap-2 text-sm"><Users size={16} className="text-muted-foreground" />Member Share Capital</div><span className="inline-flex px-2 py-1 mt-2 rounded-lg text-[9px] font-black uppercase tracking-wider bg-rose-500/10 text-rose-600 border border-rose-500/20">Liability</span></div>
                    <div className="text-right tabular-nums font-black">{formatCurrency(trialBalance.liabilities.memberShareCapital)}</div>
                  </div>
                )}
                <div className="p-4 flex items-center justify-between">
                  <div><div className="font-bold flex items-center gap-2 text-sm"><Building2 size={16} className="text-muted-foreground" />Business Capital</div><span className="inline-flex px-2 py-1 mt-2 rounded-lg text-[9px] font-black uppercase tracking-wider bg-indigo-500/10 text-indigo-600 border border-indigo-500/20">Equity</span></div>
                  <div className="text-right tabular-nums font-black">{formatCurrency(trialBalance.equity?.businessCapital || 0)}</div>
                </div>
                <div className="p-4 flex items-center justify-between">
                  <div><div className="font-bold flex items-center gap-2 text-sm"><TrendingUp size={16} className="text-muted-foreground" />Retained Earnings</div><span className="inline-flex px-2 py-1 mt-2 rounded-lg text-[9px] font-black uppercase tracking-wider bg-indigo-500/10 text-indigo-600 border border-indigo-500/20">Equity</span></div>
                  <div className="text-right tabular-nums font-black">{formatCurrency(trialBalance.equity?.retainedEarnings || 0)}</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      ) : (
        <div className="text-center py-12 bg-card rounded-3xl border border-border/50 text-muted-foreground">
          Data unavailable.
        </div>
      )}
    </div>
  );
};

export default TrialBalanceTab;
