const express = require('express');
const router = express.Router();

const routes = [
  ['/realtime', require('./realtimeRoutes')],
  ['/uploads', require('./uploadRoutes')],
  ['/auth', require('./authRoutes')],
  ['/member-auth', require('./memberAuthRoutes')],
  ['/customers', require('./customerRoutes')],
  ['/loans', require('./loanRoutes')],
  ['/groups', require('./groupRoutes')],
  ['/staff', require('./staffRoutes')],
  ['/repayments', require('./repaymentRoutes')],
  ['/ledger', require('./ledgerRoutes')],
  ['/members', require('./memberRoutes')],
  ['/subscription', require('./subscriptionRoutes')],
  ['/dashboard', require('./dashboardRoutes')],
  ['/reports', require('./reportRoutes')],
  ['/branches', require('./branchRoutes')],
  ['/contact', require('./contactRoutes')],
  ['/super-admin', require('./superAdminRoutes')],
  ['/notifications', require('./notificationRoutes')],
  ['/member-notifications', require('./memberNotificationRoutes')],
  ['/activity-logs', require('./activityLogRoutes')],
  ['/system-settings', require('./systemSettingsRoutes')],
  ['/revenue', require('./revenueRoutes')],
  ['/backup', require('./backupRoutes')],
  ['/tickets', require('./supportTicketRoutes')],
  ['/public', require('./publicRoutes')],
  ['/communication', require('./communicationRoutes')],
  ['/saving-goals', require('./savingGoalRoutes')],
  ['/search', require('./searchRoutes')],
  ['/external-transfers', require('./externalTransferRoutes')],
  ['/loan-products', require('./loanProductRoutes')],
  ['/roles', require('./roleRoutes')],
  ['/chat', require('./chatRoutes')],
  ['/checkbooks', require('./checkbookRoutes')],
  ['/ocr', require('./ocrRoutes')],
  ['/term-deposits', require('./termDepositRoutes')],
  ['/expense-categories', require('./expenseCategoryRoutes')],
  ['/aml', require('./amlRoutes')],
  ['/reviews', require('./reviewRoutes')],
  ['/scheduled-payments', require('./scheduledPaymentRoutes')],
  ['/calendar', require('./calendarRoutes')],
  ['/insights', require('./insightsRoutes')],
  ['/transfer-limit-tiers', require('./transferLimitTierRoutes')],
  ['/cash-flow-forecast', require('./cashFlowForecastRoutes')],
  ['/bulk-ops', require('./bulkOperationsRoutes')],
  ['/disputes', require('./disputeRoutes')],
  ['/device-tokens', require('./deviceTokenRoutes')],
  ['/employees', require('./employeeRoutes')],
  ['/payroll', require('./payrollRoutes')],
  ['/leaves', require('./leaveRoutes')],
  ['/attendance', require('./attendanceRoutes')],
];

routes.forEach(([path, route]) => {
  router.use(path, route);
});

module.exports = router;
